//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForecastSample.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentWeather
    {
        public int CurrentWeatherId { get; set; }
        public int LocationId { get; set; }
        public Nullable<decimal> temperature { get; set; }
        public Nullable<decimal> windspeed { get; set; }
        public Nullable<decimal> winddirection { get; set; }
        public Nullable<int> weathercode { get; set; }
        public Nullable<bool> is_day { get; set; }
        public Nullable<System.DateTime> time { get; set; }

        [JsonIgnore]
        public virtual Location Location { get; set; }
    }
}
