//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherForecastSample.DAL
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class DailyWeather
    {
        public int DailyWeatherId { get; set; }
        public int LocationId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string WeatherType { get; set; }
        public Nullable<decimal> WeatherTypeValue { get; set; }

        [JsonIgnore]
        public virtual Location Location { get; set; }
    }
}
